// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJTgdlzUQiyitqVo5LRfAYGeBW86EyemY',
    appId: '1:372544381957:web:0c531ae19c90374612686c',
    messagingSenderId: '372544381957',
    projectId: 'getmyphone',
    authDomain: 'getmyphone.firebaseapp.com',
    storageBucket: 'getmyphone.firebasestorage.app',
    measurementId: 'G-SC7QWY8RHV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyLXxyjQFdH7cTMlplq5UGR6Two_4oFWA',
    appId: '1:372544381957:android:976de59d7af0fd2c12686c',
    messagingSenderId: '372544381957',
    projectId: 'getmyphone',
    storageBucket: 'getmyphone.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAd0MnbxiWbOPH1cHaMnVgvOgib6zLOZOY',
    appId: '1:372544381957:ios:c84439e2b92c241712686c',
    messagingSenderId: '372544381957',
    projectId: 'getmyphone',
    storageBucket: 'getmyphone.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );
}
